name: Linux High-Speed Exit Node

on:
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  exit_node:
    # Use a Linux runner for kernel-level performance
    runs-on: ubuntu-latest 
    timeout-minutes: 3600

    steps:
      - name: Checkout Code (Required for using the Tailscale Action)
        uses: actions/checkout@v4

      # Key Change: Use the official Tailscale Action for reliable setup
      - name: Setup Tailscale Exit Node
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}  # OAuth is more secure, but we'll stick to auth key for simplicity
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          # Fallback to Auth Key if OAuth secrets are not configured
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          # Advertise as an exit node (the goal)
          args: --hostname=gh-linux-exit-node-${{ github.run_id }} --advertise-exit-node
          
      - name: Verify Tailscale Status
        run: |
          echo "Checking Tailscale status..."
          # The tailscale command is now in the PATH, so we don't need 'sudo' or full path
          tailscale status
          
      - name: Maintain Connection & Display Info
        run: |
          # Use the Tailscale action's output environment variable for the IP
          TS_IP=$(tailscale ip -4)
          
          echo "====================================================="
          echo "🚀 Linux Exit Node is ACTIVE and awaiting approval."
          echo "Machine Name: gh-linux-exit-node-${{ github.run_id }}"
          echo "Tailscale IP: $TS_IP"
          echo "====================================================="
          echo "REMINDER: Approve this machine as an Exit Node in the Tailscale Admin Console."
          
          # Keep runner active indefinitely (or until manually cancelled)
          while true; do
            echo "[$(date)] Exit Node Active - Use 'Cancel workflow' to terminate."
            sleep 300
          done
