name: Linux High-Speed Exit Node

on:
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  exit_node:
    # KEY CHANGE: Switches to a Linux runner for kernel-level performance
    runs-on: ubuntu-latest 
    timeout-minutes: 3600

    steps:
      - name: Install Tailscale and Connect
        run: |
          echo "Installing Tailscale..."
          # Install Tailscale on the Linux runner
          curl -fsSL https://pkgs.tailscale.com/install.sh | sh
          
          # Start Tailscale, authenticate, name the machine, and advertise the exit node
          # The --advertise-exit-node flag routes the runner's internet to your local PC
          sudo tailscale up \
            --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
            --hostname=gh-linux-exit-node-$GITHUB_RUN_ID \
            --advertise-exit-node
            
          # Get the Tailscale IP for reference
          TS_IP=$(sudo tailscale ip -4)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV
          
      - name: Maintain Connection & Display Info
        run: |
          echo "====================================================="
          echo "🚀 Linux Exit Node is ACTIVE and awaiting approval."
          echo "Machine Name: gh-linux-exit-node-$GITHUB_RUN_ID"
          echo "Tailscale IP: ${{ env.TAILSCALE_IP }}"
          echo "====================================================="
          echo "REMINDER: Approve this machine as an Exit Node in the Tailscale Admin Console."
          
          # Keep runner active indefinitely (or until manually cancelled)
          while true; do
            echo "[$(date)] Exit Node Active - Use 'Cancel workflow' to terminate."
            sleep 300
          done
