name: Linux High-Speed Exit Node (Force P2P)

on:
  # Allows you to manually trigger the workflow
  workflow_dispatch:

jobs:
  exit_node:
    # Use a Linux runner for kernel-level performance
    runs-on: ubuntu-latest 
    timeout-minutes: 3600

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Tailscale using the official action
      - name: Setup Tailscale Exit Node (Force Direct Connection)
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}
          # CRITICAL CHANGE: --test-no-derp forces P2P. --netcheck helps diagnose the runner's status.
          args: --hostname=gh-linux-exit-node-${{ github.run_id }} --advertise-exit-node --netcheck --test-no-derp
          
      - name: Verify Tailscale Status
        run: |
          echo "Checking Tailscale status..."
          tailscale status
          
      - name: Maintain Connection & Display Info
        run: |
          TS_IP=$(tailscale ip -4)
          
          echo "====================================================="
          echo "🚀 Linux Exit Node is ACTIVE. Check for Direct Connection."
          echo "Machine Name: gh-linux-exit-node-${{ github.run_id }}"
          echo "Tailscale IP: $TS_IP"
          echo "====================================================="
          echo "REMINDER: Approve this machine as an Exit Node in the Tailscale Admin Console."
          
          # Keep runner active indefinitely (or until manually cancelled)
          while true; do
            echo "[$(date)] Exit Node Active - Use 'Cancel workflow' to terminate."
            sleep 300
          done
